- name: Deploy Containers
  hosts: ec2
  become: True
  tasks:
    - name: Install Dependencies (docker)
      yum:
        name: docker
        state: present
    - name: Login AWS private repository
      cmd: aws ecr get-login-password --region sa-east-1 | docker login --username AWS --password-stdin 419466290453.dkr.ecr.sa-east-1.amazonaws.com
    - name: Pull container
      docker_container:
        name: frontend_1
        image: 419466290453.dkr.ecr.sa-east-1.amazonaws.com/rampup-repo:frontend
        state: started
        ports:
          - "3030:3030"
          - "3000:3000"
       
